Update component to hide hide asterics
vtex-apps/store-components pull request #1022
Opened 2022-03-24 18:50 UTC by albertm805

#### What problem is this solving?
- Asterics in the `UserAddres` is always shown. The user should have the option to disable this.

- A client is requesting us to remove the asteriscs from the `UserAddress` component. 
- I added a new prop to hide this from the component.

#### How to test it?

This feature can be tested [here](https://beto--sandboxusdev.myvtex.com/)

#### Screenshots or example usage:

![Image 2022-03-23 at 11 35 22 p m](https://user-images.githubusercontent.com/11176519/159980776-c007d87d-9b14-436d-83a1-d59112f6bcb8.jpg)

2022-03-24 19:10 UTC, polishq requested changes

2022-03-24 19:10 UTC, polishq commented on react/UserAddress.tsx
> +  showIfHidden?: boolean
```suggestion
  showIfMasked?: boolean
```

2022-03-24 19:10 UTC, polishq commented on react/UserAddress.tsx
> +          showIfHidden={showIfHidden}
```suggestion
          showIfMasked={showIfMasked}
```

2022-03-24 19:24 UTC, albertm805 commented on react/components/UserAddress/AddressInfo.tsx
> +      : '' }${showPostalCode && showIfHidden ? postalCode : ''}`
Yes this could be another option to avoid displaying info.

2022-03-24 19:43 UTC, polishq commented
LGTM but I'll leave it up to @vtex-apps/store-framework-devs to approve

2022-03-25 18:18 UTC, victorhmp approved these changes

2022-03-28 17:50 UTC, merged