refactor query fetch and add position data
vtex-apps/store-components pull request #1041
Opened 2022-07-08 11:17 UTC by spclu6

#### What problem is this solving?

This pr tries to solve the following:

- Uses the hook useDevice of the app 'vtex.device-detector' which returns more accurately what type of device the user is on than the one currently in use.

- It avoids the Graphql query to be performed every time the component is rendered thus avoiding to make calls before it loads the minimum information to obtain the personalized images.

- It refactors the way in which the latitude and longitude of the user can be obtained extracting that logic in a custom hook so that the Image component is cleaner.

#### How to test it?

[Workspace](https://imageprotocol--spclusellas.myvtex.com/?__bindingAddress=spclusellas.myvtex.com/)

#### Describe alternatives you've considered, if any.

An alternative that is being explored is to directly obtain the user's location through the ip in the backend and thus avoid waiting time on the client.

2022-07-11 10:48 UTC, tomymehdi requested changes

2022-07-11 10:48 UTC, tomymehdi commented on react/components/InfoCard/index.js
> +      ssr: false,
why are we forcing the client side rendering?

2022-07-11 10:48 UTC, tomymehdi commented on react/hooks/usePosition.ts
> +interface Coordinate {
let's replace `Coordinate` for `LatLong`. `Coordinate` is confusing

2022-07-11 10:48 UTC, tomymehdi commented on react/hooks/usePosition.ts
> +interface Position {
Maybe something like `LatLongRecord`, `LatLongHistory` or `LatLongTime` is a better fit here

2022-07-12 08:37 UTC, LeslieJRP approved these changes
changes reviewed

2022-07-12 09:08 UTC, merged