feat(acessibility): added ARIA-label property to resolve accessibilit…
vtex-apps/store-components pull request #1096
Opened 2023-10-09 14:42 UTC by joaocongio

#### What problem is this solving?

Adicionado a propriedade aria-label para melhorar experiência de leitores de tela e resolver ajustes de acessibilidade apontados pelo Lighthouse.

#### How to test it?

[Workspace](https://www.samsclub.com.br/?workspace=testeacessibilidade)

#### Screenshots or example usage:

![Search After](https://github.com/vtex-apps/store-components/assets/22462037/a50a7f68-125b-41bc-bbe0-5ccc4e451f31)

![Search Before](https://github.com/vtex-apps/store-components/assets/22462037/8e22a731-72bd-4b24-bb47-386837faffc6)

2023-10-09 14:42 UTC, joaocongio commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2023-10-09 14:49 UTC, joaocongio commented
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

2023-11-01 00:03 UTC, filipewl requested changes
Opa João, muito obrigado pelas melhorias!

Deixei alguns comentários que precisam ser vistos antes de prosseguir. Dá uma lida e qualquer estarei aqui pra tirar dúvidas.

2023-11-01 00:03 UTC, filipewl commented on react/components/SearchBar/AutocompleteInput.tsx
> +      aria-label="Search Products"
Para esses `aria-label`s, precisaremos [permitir as diversas traduções](https://developers.vtex.com/docs/guides/external-marketplace-integration-app-template#step-3-translating-a-component), para não deixar essas strings hardcoded em inglês.

Se você buscar por `intl.formatMessage` dentro do projeto você encontrará exemplos de como usar. A princípio será preciso:

1. Importar o hook `useIntl` do `react-intl` neste arquivo e inicializá-lo dentro deste componente.
2. Chamar o resultado de `intl.formatMessage({ id: 'store/search.[submit-query|clear-input]' })` nos valores usados pelo `aria-label`.
3. Criar novas chaves nos arquivos dentro de `messages/[pt|en|es|*].json` com as traduções das palavras novas, e.g., `store/search.submit-query` para a descrição do botão de submeter a busca e `store/search.clear-input` para o botão de apagar o campo.
	- Acredito que a priori só precisamos das traduções para o inglês, português, e espanhol. Posteriormente abrirei um pedido interno pro restante das trações.

Exemplo:
![CleanShot 2023-10-31 at 20 57 55](https://github.com/vtex-apps/store-components/assets/381395/bb9c51dd-24bd-4e75-94bf-ca1490c1aecd)

Achas que consegues fazer isso?

2023-11-07 15:31 UTC, joaocongio commented on react/components/SearchBar/AutocompleteInput.tsx
> +      id="closeIcon"
"Quando um botão não tem um nome acessível, os leitores de tela o enunciam como "botão", o que o inutiliza para usuários que dependem desses leitores. [Aprenda a tornar os botões mais acessíveis](https://dequeuniversity.com/rules/axe/4.7/button-name)."

A utilização do id e aria-label juntos para os botões, são uma boa prática. Mas podemos também remover a propriedade id e manter apenas aria-label.

2023-11-07 15:32 UTC, joaocongio commented on react/components/SearchBar/AutocompleteInput.tsx
> +      aria-label="Search Products"
Ajuste feito!

2023-11-14 13:21 UTC, joaocongio commented on react/components/SearchBar/AutocompleteInput.tsx
> +      aria-label="Search Products"
@filipewl conseguiu dar uma olhada nos ultimos ajustes?
Obrigado.

2024-01-04 12:18 UTC, gvc commented on react/components/SearchBar/AutocompleteInput.tsx
> +      id="closeIcon"
@joaocongio podes seguir com a remoção dos ids? Já que estamos colocando de forma incondicional os `aria-label`, acredito que deixar sem o `id` é melhor até por que os usuários não terão controle sobre o id e pode conflitar com outro elemento na página.

2024-01-08 18:36 UTC, joaocongio commented on react/components/SearchBar/AutocompleteInput.tsx
> +      id="closeIcon"
@gvc propriedade id removida. Pode verificar novamente, por favor?

2024-01-08 21:02 UTC, gvc approved these changes

2024-01-09 18:24 UTC, merged