add width and height in <img>
vtex-apps/store-components pull request #1105
Opened 2024-04-30 19:52 UTC by lucvysk

#### What problem is this solving?

add width and height in img to improve CLS

#### How to test it?

https://vysk2--hunterdouglasnl.myvtex.com/

#### Screenshots or example usage:

<img width="1604" alt="image" src="https://github.com/vtex-apps/store-components/assets/25616893/07ac016e-5594-41ea-977a-f0956c744661">

<img width="1262" alt="image" src="https://github.com/vtex-apps/store-components/assets/25616893/bb9db23b-2398-4ed6-bdf6-0c2ce1ad1249">

2024-07-04 15:45 UTC, mateussaggin approved these changes
LGTM

2024-07-15 14:32 UTC, vmourac-vtex requested changes
Minor change required
 - Missing localization key (see review)
 - Missing documentation for the new parameters in `InfoCard.md`

2024-07-15 14:33 UTC, vmourac-vtex requested changes
Minor change required
 - Missing localization key (see review)
 - Missing documentation for the new parameters in `InfoCard.md`

2024-10-16 13:29 UTC, lucvysk commented
> Minor change required
> 
> * Missing localization key (see review)
> * Missing documentation for the new parameters in `InfoCard.md`

Done!

2026-04-20 15:06 UTC, closed without merging