Add img props to infoCard component
vtex-apps/store-components pull request #1112
Opened 2024-08-07 15:38 UTC by diegoleone

#### What problem is this solving?

Currently we do not support `fetchPriority` & `preload` props for images within the native infoCard component. Therefore, I am adding those props, to allow better management of those assets. The implementation follows the example used in the vtex.store-image native component.
https://github.com/vtex-apps/store-image/blob/master/react/Image.tsx

#### How to test it?

Visit the Dunnes store in this workspace: https://preloadimg--dunnesstorespreprod.myvtex.com/

<img width="339" alt="Screenshot 2024-08-07 at 12 36 11" src="https://github.com/user-attachments/assets/ad3325c9-c86e-43bc-a654-089a377e3997">

2024-08-07 15:40 UTC, beatrizmaselli commented
@diegoleone thanks for your contribution! Could you please update the docs folder with this new prop for the infoCard and add a changelog for this change? Thanks ✨

2024-08-07 15:43 UTC, beatrizmaselli commented on react/components/InfoCard/index.js
> +  preload
Please add the comma here or run a `yarn lint --fix`

2024-08-07 16:18 UTC, beatrizmaselli approved these changes
LGTM

2024-08-13 19:05 UTC, iago1501 requested changes
Just a type fix

2024-08-13 19:05 UTC, iago1501 commented on react/components/InfoCard/index.js
> +  preload: '',
Since this is a boolean, this prop should be false and not line in isFullModeStyle ''

2024-08-13 19:07 UTC, iago1501 commented on react/components/InfoCard/index.js
> +  preload: '',
```suggestion
  preload: false,
```

2024-08-13 19:16 UTC, diegoleone commented
@iago1501 Thank you. All done.

2024-08-14 14:26 UTC, iago1501 approved these changes
LGTM

2024-08-15 17:32 UTC, merged