Configurable thumbnail dimensions in product gallery
vtex-apps/store-components pull request #1120
Opened 2024-09-17 14:46 UTC by gabridevs

#### What problem is this solving?

This PR adds the ability to configure the width and height of product thumbnails in the carousel component. By allowing control over the thumbnail dimensions, this can improve page performance and SEO by ensuring that appropriately sized images are used, reducing unnecessary data loading.

#### How to test it?

You can test this feature by setting custom values for thumbCustomWidth and thumbCustomHeight in the product image gallery component. Ensure that thumbnails are resized correctly based on these values, and monitor the impact on page load times and SEO scores.

For test use this [Workspace](https://pr31410--italiaonlineqa.myvtex.com)

#### Screenshots or example usage:

In production:
Official component in production unable to set thumbnail size.
See props: [Product Image](https://developers.vtex.com/docs/apps/vtex.store-components/ProductImages)

In workspace:

<img width="1492" alt="Screenshot 2024-09-17 alle 16 25 54" src="https://github.com/user-attachments/assets/8bdc99ca-1250-4519-836f-98c3ba9fe58d">

can be able to set values in px from props component:
<img width="518" alt="Screenshot 2024-09-17 alle 16 43 40" src="https://github.com/user-attachments/assets/671f16b3-9901-4813-b473-8eabdd6ee300">

#### Describe alternatives you've considered, if any.

An alternative approach considered was to use CSS only for thumbnail resizing, but this would not allow for dynamic configuration through props or tailored image dimensions for performance.

#### Related to / Depends on

No dependencies.

2024-09-17 14:49 UTC, gabridevs commented
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
>     * [ ]  There's nothing new to document 🤔
> 
>     * [ ]  I'll do it later 😞
> 
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
>     * [x]  I just updated 🎉🎉

2025-05-21 21:13 UTC, vmourac-vtex requested changes
Add documentation to the corresponding component in `docs` folder

2025-05-21 21:13 UTC, vmourac-vtex commented on react/components/ProductImages/Wrapper.js
> +      thumbCustomHeight={thumbCustomHeight}
Please add documentation for the new props in [docs/ProductImages.md](https://github.com/vtex-apps/store-components/blob/master/docs/ProductImages.md)

2025-05-21 21:14 UTC, vmourac-vtex commented on react/components/ProductImages/Wrapper.js
> +      thumbCustomHeight={thumbCustomHeight}
Also, please update your source branch to avoid merge conflicts with `CHANGELOG.md`

2025-06-06 13:36 UTC, vmourac-vtex commented
@gabridevs the workspace provided in the PR is not working. 
Please update the PR description with a proper workspace and detailed step by step procedures do reproduce the behavior

2025-06-24 18:56 UTC, gabridevs commented
> @gabridevs the workspace provided in the PR is not working. Please update the PR description with a proper workspace and detailed step by step procedures do reproduce the behavior

Hi @vmourac-vtex, the worksoace is now working again. Check please

2025-06-24 20:17 UTC, gabridevs commented on react/components/ProductImages/Wrapper.js
> +      thumbCustomHeight={thumbCustomHeight}
Hi @vmourac-vtex, i have update docs for ProductImages.md. Can u check please ?

2025-07-16 13:26 UTC, closed without merging

2025-07-16 14:25 UTC, gabridevs commented
hi @vmourac-vtex , i opened a new PR for this scenario and i create a separate branch for pr:
https://github.com/vtex-apps/store-components/pull/1140