Chore/ts migrate
vtex-apps/store-components pull request #870
Opened 2020-10-02 18:44 UTC by kaisermann

#### What problem is this solving?

Initial migration to TypeScript started by @victorhmp by using https://github.com/airbnb/ts-migrate.

As discussed in our daily at (01/10/2020), initially I was thinking of having a single gigantic PR with all the correct typescript code. However, this will be a lot difficult to make in a single PR, as we have to fix errors in other projects as well. This branch was linked and tested in the workspace mentioned below. After merging, the next steps are smaller prs fixing the `// @ts-expect-error` comments we have throughout the whole codebase.

#### How to test it?

https://tsmigrate--storecomponents.myvtex.com/?

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/1RkDDoIVs3ntm/giphy.gif)

2020-10-05 11:30 UTC, guerreirobeatriz approved these changes

2020-10-05 19:06 UTC, iaronaraujo reviewed
Could this break if the previous proptypes didn't have all the props?
Also, the migration tool left a bunch of comments, it would be nice to check if we can remove them.

2020-10-08 18:55 UTC, klzns requested changes

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/Container.test.tsx
> +  const renderComponent = (customProps: any) => {
```suggestion
  const renderComponent = (customProps?: any) => {
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/CategoriesHighlights.test.tsx
> +  const renderComponent = (customProps: any) => {
```suggestion
  const renderComponent = (customProps?: any) => {
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/CategoriesHighlights.test.tsx
> +    // @ts-expect-error ts-migrate(2554) FIXME: Expected 1 arguments, but got 0.
Remove this if suggestion above is accepted
```suggestion
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/CategoriesHighlights.test.tsx
> +    // @ts-expect-error ts-migrate(2554) FIXME: Expected 1 arguments, but got 0.
```suggestion
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/BuyButton.test.tsx
> +  const renderComponent = (customProps: any, text = 'Test') => {
Add optional for the second argument too
```suggestion
  const renderComponent = (customProps?: any, text = 'Test') => {
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/BuyButton.test.tsx
> +    // @ts-expect-error ts-migrate(2554) FIXME: Expected 1-2 arguments, but got 0.
```suggestion
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/Container.test.tsx
> +    // @ts-expect-error ts-migrate(2554) FIXME: Expected 1 arguments, but got 0.
```suggestion
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/Container.test.tsx
> +    // @ts-expect-error ts-migrate(2554) FIXME: Expected 1 arguments, but got 0.
```suggestion
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/Greeting.test.tsx
> +  const renderComponent = (customProps: any) => {
```suggestion
  const renderComponent = (customProps?: any) => {
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/Greeting.test.tsx
> +    // @ts-expect-error ts-migrate(2554) FIXME: Expected 1 arguments, but got 0.
```suggestion
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/InfoCard.test.tsx
> +  const renderComponent = (props: any) => {
```suggestion
  const renderComponent = (props?: any) => {
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/InfoCard.test.tsx
> +    // @ts-expect-error ts-migrate(2554) FIXME: Expected 1 arguments, but got 0.
```suggestion
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/Logo.test.tsx
> +  const renderComponent = (customProps: any) => {
```suggestion
  const renderComponent = (customProps?: any) => {
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/Logo.test.tsx
> +    // @ts-expect-error ts-migrate(2554) FIXME: Expected 1 arguments, but got 0.
```suggestion
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/ProductDescription.test.tsx
> +  const renderComponent = (customProps: any) => {
```suggestion
  const renderComponent = (customProps?: any) => {
```

2020-10-08 18:55 UTC, klzns commented on react/__tests__/components/ProductName.test.tsx
> +  const renderComponent = (customProps: any) => {
same

2020-10-08 18:55 UTC, klzns commented on react/components/ShippingSimulator/components/ShippingTable.tsx
> +type Props = {
```suggestion
interface Props {
```

2020-10-16 18:02 UTC, kaisermann commented
Will do this one by one

2020-10-16 18:02 UTC, closed without merging