Migrate Logo components to TypeScript
vtex-apps/store-components pull request #894
Opened 2020-11-26 15:15 UTC by victorhmp

#### What problem is this solving?

Components under the `react/components/ProductBrand` directory were not written in TypeScript yet, this PR solves that 🎉 .

#### How to test it?

[Workspace](https://logotypescript--storecomponents.myvtex.com/)

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/l4FB5dgbc21nQPKhy/giphy.gif)

2020-11-26 15:42 UTC, klzns approved these changes

2020-11-26 19:01 UTC, kaisermann approved these changes

2020-11-27 19:13 UTC, icazevedo approved these changes

2020-12-01 18:46 UTC, klzns requested changes

2020-12-01 18:46 UTC, klzns commented on react/Logo.tsx
> +  height: string | number
Optional

2020-12-01 18:46 UTC, klzns commented on react/Logo.tsx
> +  mobileHeight: string | number
Optional

2020-12-01 21:14 UTC, klzns requested changes
rebase pls

2020-12-02 17:20 UTC, klzns approved these changes

2020-12-02 19:49 UTC, merged