Feature: SKU Selector `displayPrices` prop
vtex-apps/store-components pull request #897
Opened 2020-12-02 21:04 UTC by juliomoreira

#### What problem is this solving?

-  Adds the option to show the SKU variation price in SKU Selector. This is best suited when `displayMode` is set to `select` but it works as well in `default` mode as shown bellow;

#### How to test it?

1. Open [Workspace](https://juliomoreira--drinkrunnr.myvtex.com/);
1. Scroll until the section "Summer";
1. Interact with the SKU Selector;
1. Observe that the item price is showing;

#### Screenshots or example usage:

##### Product Summary

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/1207017/100929775-e5e39b80-34c6-11eb-91a8-66867c5b1a3f.gif)

##### Product Page

![Screen Shot 2020-12-02 at 17 31 13](https://user-images.githubusercontent.com/1207017/100929937-22af9280-34c7-11eb-9011-b2ed0475d213.png)

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/7WyUkDrDlOFf1Q8ODi/giphy.gif)

2020-12-03 13:10 UTC, juliomoreira commented
Related to Issue: https://github.com/vtex-apps/store-components/issues/875

2020-12-07 11:48 UTC, guerreirobeatriz requested changes

2020-12-07 11:48 UTC, guerreirobeatriz commented on docs/SKUSelector.md
> +| `displayPrices`     | `boolean` | Only works if `displayMode` is set to `select` or `default`. Display the product price next to the variation label. Examples: [Shelf](https://user-images.githubuse
```suggestion
| `displayPrices`  | `boolean` | Whether the product price should be displayed next to the variation label (`true`) or not (`false`) - you can find practical examples of this prop working on a shelf and a product details page, respectively, [here](https://user-images.githubusercontent.com/1207017/100927937-550bc080-34c4-11eb-9a2f-d0421f00e11b.png) and [here](https://user-images.githubusercontent.com/1207017/100927940-56d58400-34c4-11eb-911f-062c2f227511.png). *Caution*: This prop only works if the `displayMode` prop is set as `select` or `default`.  | `false` |
```

2020-12-08 12:52 UTC, guerreirobeatriz approved these changes

2020-12-08 21:32 UTC, kaisermann requested changes

2020-12-08 21:32 UTC, kaisermann commented on react/components/SKUSelector/components/SelectVariationMode.tsx
> +  // @ts-ignore
This is not needed now. Run `vtex setup --typings` and you should be good to go

2020-12-08 21:32 UTC, kaisermann commented on react/components/SKUSelector/components/SelectVariationMode.tsx
> +    }
```suggestion
  if (displayPrices && value && selectedItem !== label) {
    return {
      label: `${label} - ${formatCurrency({ intl, culture, value })}`,
      value: label,
    }
  }

  return { label, value }
```

2020-12-08 21:59 UTC, icazevedo requested changes
The new prop should not be a boolean, but an enum. Maybe with `'current'` as a possible value, that would indicate that it will show the current prince, and being possibly undefined (default case).

2024-08-26 17:47 UTC, closed without merging