Adding withLink prop to ProductBrand
vtex-apps/store-components pull request #899
Opened 2020-12-04 18:14 UTC by icazevedo

#### What problem is this solving?

This PR adds the ability to use links when the ProductBrand mode is set to `text` or fallback to text by using the `withLink` prop. It also deprecates the previous `logoWithLink` prop in favor of the new, more flexible one.

#### How to test it?

Any product on this [workspace](https://icaroproductbrand--storecomponents.myvtex.com/).

#### Screenshots or example usage:

<img width="462" alt="Screen Shot 2020-12-04 at 3 10 14 PM" src="https://user-images.githubusercontent.com/8127610/101198820-d1c4a900-3642-11eb-822c-384eecd2a233.png">

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/NVBR6cLvUjV9C/giphy.gif)

2020-12-04 18:30 UTC, kaisermann approved these changes

2020-12-04 19:48 UTC, vitorflg approved these changes

2020-12-07 12:26 UTC, guerreirobeatriz requested changes

2020-12-07 12:26 UTC, guerreirobeatriz commented on docs/ProductBrand.md
> +| `brandId` | `Number` | The brand id. If this value is not passed, it will be obtained through the product context. | `undefined` |
```suggestion
| `withLink` | `enum` | Defines the scenarios in which the product brand should have a link that leads to its website. Possible values are: `none` (never displays the link), `logo` (displays the link whenever the brand logo is displayed), `text` (displays the link whenever the brand name is displayed), and `logoAndText` (displays the link whenever the brand logo or the brand name is displayed).  | `none` |
| `brandName` | `string` | The brand name. If no value is declared, the product context should provide the data. | `undefined` |
| `brandId` | `number` | The brand ID.  If no value is declared, the product context should provide the data. | `undefined` |
```

2020-12-08 14:47 UTC, guerreirobeatriz approved these changes

2020-12-08 19:59 UTC, merged