possibleToClickOnImpossibleCombination
vtex-apps/store-components pull request #986
Opened 2021-10-21 20:26 UTC by anamaiabap

**What problem is this solving?**
This PR allows the possibility to click in the option "impossibles" on store if you want to.

**How to test it?**
**Before**:
https://skubefore--anamb.myvtex.com/camisa/p?skuId=7
**After**:
https://sku--anamb.myvtex.com/camisa/p?skuId=7

**Screenshots or example usage:**
**Before**
<img width="475" alt="Captura de Tela 2021-10-22 às 17 10 57" src="https://user-images.githubusercontent.com/80836180/138516962-7b133872-5e7f-47d7-9073-e181f8cc9326.png">

**After**
<img width="577" alt="Captura de Tela 2021-10-21 às 16 56 50" src="https://user-images.githubusercontent.com/80836180/138348107-9ab34d16-b65e-4c38-9221-b7802f8178ad.png">

It's also possible to use the option "all" if you want the same demeanor in all of the specifications. 
<img width="615" alt="Captura de Tela 2021-10-21 às 16 56 21" src="https://user-images.githubusercontent.com/80836180/138348094-cbe2b7f9-ecdb-4e38-833c-a3fa03757ba2.png">

Then, just visit your store and test the new function. 

![Gravação-de-Tela-2021-10-21-às-17 02 55](https://user-images.githubusercontent.com/80836180/138351731-6cbad9bc-5d55-43df-8915-042fb7d2a245.gif)

2021-11-17 12:24 UTC, igorbrasileiro commented on react/components/SKUSelector/components/SKUSelector.tsx
> +        newObject as SelectedVariations
Isn't it preferable to type the newObject as SelectedVariations?

2021-11-17 12:26 UTC, igorbrasileiro commented on react/components/SKUSelector/components/SKUSelector.tsx
> +const parseOptionNameToDisplayOption =
This method seems to be too huge. Can we split it into some meaningful functions?

2021-11-18 21:14 UTC, igorbrasileiro approved these changes

2021-12-03 16:02 UTC, icazevedo requested changes
Functionality wise, LGTM, but the code needs adjustments. Also, undo all changes to the changelog and just add your entry. You shouldn't edit/reformat past changelogs.

2024-08-26 17:47 UTC, closed without merging